# Generated by Django 3.0.2 on 2020-08-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('available', 'Person available'), ('overloaded', 'Person overloaded')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('importance', models.DecimalField(decimal_places=0, max_digits=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='todo.Person')),
            ],
        ),
    ]
