# Generated by Django 2.2.9 on 2020-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_address', models.URLField(max_length=1000)),
                ('passed_expression', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Searchtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_text', models.TextField(max_length=10000)),
                ('passed_phrase', models.CharField(max_length=100)),
            ],
        ),
    ]
